server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3308/moviematch_db
spring.application.name=moviematch
spring.datasource.username=root
spring.datasource.password=ifsp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0
jwt.secret=moviematch_bradwbk_anajulia_isabelly